# Generated by Django 5.2.9 on 2025-12-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_auto_20251210_0010"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("Random Thoughts", "Random Thoughts"),
                    ("School", "School"),
                    ("Personal", "Personal"),
                ],
                default="Random Thoughts",
                max_length=50,
            ),
        ),
    ]
