# Generated by Django 4.2.20 on 2025-12-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.CharField(
                choices=[
                    ("Random Thoughts", "Random Thoughts"),
                    ("School", "School"),
                    ("Personal", "Personal"),
                    ("Drama", "Drama"),
                ],
                default="Random Thoughts",
                max_length=50,
            ),
        ),
    ]
